### ISSUE TITLE
Signal CFN on jenkins instance deploy

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/jenkins-quick-deploy#2]
Background:
If CloudFormation updates the stack, but the Jenkins instance isn't valid, then we'll have a broken deploy. To prevent this, we want to stack to fail if Jenkins fails to launch correctly

ToDo:
Add a creation policy to the Jenkins AWS EC2 Instance. That policy should wait to be signaled before declaring that the EC2 instance is created. In userdata, have the last command be a signal to CloudFormation that the ec2 instance is running. This'll cause failure if the previous steps don't succeed.

DoD:
- CloudFormation has a CreationPolicy on the Jenkins EC2 Instance
- The EC2 userdata uses CFN signal to call back to the stack

**Comment by davidrfreeman** [comment]
Added creation policy to EC2 instance and cfn-signal script to UserData.
Commit SHA 8cef2991913e7c7bd9c69745deb9a462cfd82ae1
