### ISSUE TITLE
Berks vendor fails in user data

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/jenkins-quick-deploy#3]
Background:
Before using Chef to bootstrap an EC2 instance, all cookbooks need to be put in a single place. This way, Chef knows how to reference dependent cookbooks. To accomplish this, we use Berks vendor

ToDo:
Figure out why the berks vendor command in jenkins.yml fails to run. Update the userdata script to correctly install all cookbooks in the desired directory (doesn't matter where). and then confirm that Chef will run them

DoD:
- Berks installs cookbooks using the command `berks vendor`
- Chef is able to run the cookbooks defined in /home/ubuntu/node.json

**Comment by davidrfreeman** [comment]
Updated HOME var before Berks command

**Comment by davidrfreeman** [comment]
Updated HOME var before Berks command
